### ISSUE TITLE
Don't think it's right

### ISSUE THREAD

**Issue by Vnuuk** [VladislavKozlov/Todo#12]
![image](https://user-images.githubusercontent.com/1075983/74070928-6fdfe680-4a13-11ea-99b4-573710740992.png)

Let's discuss on Skype

**Comment by Vnuuk** [comment]
I think everything is wrong in this method

![image](https://user-images.githubusercontent.com/1075983/74070996-9f8eee80-4a13-11ea-8737-5ed1e5ab7daa.png)

**Comment by VladislavKozlov** [comment]
This request has been completed.
