### ISSUE TITLE
You should have separate folders for models

### ISSUE THREAD

**Issue by Vnuuk** [VladislavKozlov/Todo#15]
![image](https://user-images.githubusercontent.com/1075983/74071215-4e332f00-4a14-11ea-8f4e-c2e53a295840.png)

Same for components and services

**Comment by VladislavKozlov** [comment]
This request has been completed.

**Comment by Vnuuk** [comment]
![image](https://user-images.githubusercontent.com/1075983/74221182-8b244d80-4cc2-11ea-98b2-6c303313a821.png)

Let's name folder in lower case in UI project

**Comment by VladislavKozlov** [comment]
This request has been completed.
