### ISSUE TITLE
Replace SingleOrDefault with FirstOrDefault

### ISSUE THREAD

**Issue by Vnuuk** [VladislavKozlov/Todo#7]
![image](https://user-images.githubusercontent.com/1075983/74070652-a832f500-4a12-11ea-8904-8966d06b28bf.png)

Also let's discuss the difference in Skype

**Comment by Vnuuk** [comment]
+ Get rid of comment above the method definition

**Comment by VladislavKozlov** [comment]
This request has been completed.
