### ISSUE TITLE
Return status code "Not Found" instead of null

### ISSUE THREAD

**Issue by Vnuuk** [VladislavKozlov/Todo#8]
![image](https://user-images.githubusercontent.com/1075983/74070716-de707480-4a12-11ea-8a4c-9b7b57043c32.png)

**Comment by VladislavKozlov** [comment]
This request has been completed.

**Comment by Vnuuk** [comment]
Do not see your implementation. It simply returns bull if nothing has found..

**Comment by VladislavKozlov** [comment]
This request has been completed.

**Comment by Vnuuk** [comment]
![image](https://user-images.githubusercontent.com/1075983/74430851-c06d9e80-4e6e-11ea-9a4e-66be1814898f.png)

You miss something when you use async / await feature

**Comment by VladislavKozlov** [comment]
This request has been completed.

**Comment by Vnuuk** [comment]
![image](https://user-images.githubusercontent.com/1075983/74636482-1e54fb80-5179-11ea-83ce-7f8310be0caf.png)

Service interface is still wrong. Service should not return Action Result

**Comment by VladislavKozlov** [comment]
This request has been completed.
